FROM ubuntu:latest

ENV TZ=Asia/Kolkata
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# LLVM dependencies:
RUN apt-get update ; apt-get install --no-install-recommends \
    -y \
    autoconf \
    automake \
    ca-certificates \
    cmake \
    libfreetype6-dev \
    g++ \
    gcc \
    time \
    libxml2-dev \
    make \
    musl-dev \
    ninja-build \
    libncurses5-dev libncursesw5-dev \
    python3 \ 
    python3-dev \
    nano \
    git \
    wget

WORKDIR /
RUN git clone --progress --verbose --depth 1 https://github.com/llvm/llvm-project.git

RUN cd llvm-project ; cmake -S llvm -B build -G "Ninja" \
    -DLLVM_ENABLE_PROJECTS="llvm;clang;compiler-rt" \
    -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
    -DCMAKE_BUILD_TYPE=Release \
    -DLLVM_INSTALL_UTILS=ON ; cd build ; ninja all ; ninja install

RUN git clone https://github.com/lahiri-phdworks/LLVM-Examples

ENV CXX=/llvm-project/build/bin/clang++
ENV CC=/llvm-project/build/bin/clang
ENV OPT=/llvm-project/build/bin/opt
ENV HOME=
ENV LLVM_BUILD_PATH=/llvm-project/build
ENV LLVM_BIN_DIR=/llvm-project/build/bin